[package]
name = "day06"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
anyhow = "1.0.75"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"