name: Update README ⭐
on:
  schedule:
    - cron: "51 */4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Udate README
        uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2403535
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2023
      
      - name: Commit README changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars